<h1>Cadastrar Produtos</h1>

<form method="POST" action="\index/cadastrar">
	
	<div class="row">

		<div class="col-md-6 col-sm-6">
			<div class="form-group">
				<label>Nome</label>
				<input required="true" type="text" name="nome" class="form-control" />
			</div>
			<div class="form-group">
				<label>Preco</label>
				<input required="true"  type="number" name="preco" class="form-control" />
			</div>
			<div class="form-group">
				<label>Descricao</label>
				<textarea required="true" class="form-control" name="descricao"></textarea>
			</div>

			<input type="submit" class="btn btn-primary" value="Salvar Produto" />
		</div>

	</div>


</form>